# docker-compose.yaml
version: "3"

services:
  frontend:
    image: registry.cn-shanghai.aliyuncs.com/d2jvkpn/rust-web-frontend:${TAG}
    container_name: rust-web-frontend_${APP_ENV}
    restart: always
    # network_mode: bridge
    # network_mode: host
    networks: ["net"]
    ports: ["${PORT}:80"]
    # ./configs.json:/opt/nginx-web/dev/configs.json
    # ./configs.json:/opt/nginx-web/configs.json
    environment:
    - TZ="Asia/Shanghai"
    - NGINX_PORT=80

networks:
  net:
    name: rust-web-frontend_${APP_ENV}
    driver: bridge
    external: false
